common: include file and line number in scx_bpf_error
scx_bpf_error takes a user provided format string and args to exit the scheduler
with an error. When deploying a scheduler at scale this can be tricky to convert
back to a line of code. Add the `__FILE__` and `__LINE__` macros to give us a
fighting chance of finding the line the error occurred on.

Uses string literal concatenation rather than printf parameters to avoid using
up the 6 argument limit in BPF-C. This string should end up as a compile time
constant instead of on the BPF stack, and is passed directly to the kfunc.

Test plan:
- Built everything (local for Rust & CI for all).

Tested by injecting a failure into p2dq. Before:

    Error: EXIT: scx_bpf_error (failed)

After:

    Error: EXIT: scx_bpf_error (src/bpf/main.bpf.c:1047: failed)